[package]
name = "house_status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.12"
local-ip-address = "0.4.9"
sysinfo = "0.26.7"
